name: LibreNZ
vyos_branch: sagitta
modules:
  - type: git
    url: https://github.com/ToroNZ/vyos-module-tailscale.git
    version: current
  - type: git
    url: https://github.com/ToroNZ/vyos-module-speedtest.git
    version: main
  - type: git
    url: https://github.com/ToroNZ/vyos-module-gitops.git
    version: saggita
