name: 'Compile and create new VyOS Release'

on:
  workflow_dispatch:
  push:
    branches:
      - toronz-main

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Build ISO
        run: python main.py -c config.yml
      - name: Rename ISO
        run: mv bin/vyos-*.iso bin/vyos-${{ github.job_workflow_sha }}.iso
      - uses: actions/upload-artifact@v3
        with:
          name: vyos
          path: bin/vyos-${{ github.job_workflow_sha }}.iso
  release:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/download-artifact@master
        with:
          name: vyos
          path: bin/vyos-${{ github.job_workflow_sha }}.iso
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "She'll be alright kinda build"
          files: bin/vyos-${{ github.job_workflow_sha }}.iso
