name: 'Compile and create new VyOS Release'

on:
  workflow_dispatch:
  push:
    branches:
      - toronz-main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Build ISO
        run: python main.py -c config.yml
      - uses: actions/upload-artifact@v3
        with:
          name: vyos
          path: build/vyos-*.iso
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: vyos
          path: build/vyos-*.iso
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "She'll be alright kinda build"
          files: build/vyos-*.iso
