name: 'Compile and create new VyOS Release'

on:
  schedule: 
    - cron: '15 10 7 * *' # Runs at 10:15, on day 7 of the month.
  workflow_dispatch:
  push:
    branches:
      - toronz-main
    paths-ignore:
      - ".github/**"
      - "**.md"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Build ISO
        run: python main.py -c config.yml
      - name: Rename ISO
        run: mv bin/vyos-*.iso bin/vyos-$(date +'%Y%m%d%H%M%S').iso
      - uses: actions/upload-artifact@v3
        with:
          name: vyos
          path: bin/vyos-*.iso
          retention-days: 1
          if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/download-artifact@master
        with:
          name: vyos
          path: bin/vyos-*.iso
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "She'll be alright kinda build"
          files: bin/vyos-*.iso
